-- RentHub pilot schema for Supabase.
-- The Node pilot currently uses SQLite locally; this file covers hosted pilot data.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  avatar text,
  city text,
  province text,
  is_owner boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  icon text default '',
  color text default '',
  is_active boolean not null default true
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id),
  title text not null,
  description text not null default '',
  price_per_day integer not null check (price_per_day > 0),
  estimated_value integer not null default 0 check (estimated_value >= 0),
  security_deposit integer not null default 0,
  location_city text not null,
  location_province text default '',
  condition text default '',
  accessories text default '',
  rules text default '',
  status text not null default 'active' check (status in ('draft', 'active', 'paused', 'removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  url text not null,
  is_primary boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  link text not null default '',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "published listings are public" on public.listings;
drop policy if exists "owners manage their listings" on public.listings;
drop policy if exists "listing images are public" on public.listing_images;
drop policy if exists "owners manage listing images" on public.listing_images;
drop policy if exists "users manage their profile" on public.profiles;
drop policy if exists "categories are public" on public.categories;
drop policy if exists "participants read messages" on public.messages;
drop policy if exists "users send messages" on public.messages;
drop policy if exists "users read notifications" on public.notifications;
drop policy if exists "users mark notifications read" on public.notifications;

-- Cast both sides to text so this remains compatible with pilot tables created
-- earlier with text user IDs instead of UUID columns.
create policy "published listings are public" on public.listings for select using (status = 'active' or owner_id::text = auth.uid()::text);
create policy "owners manage their listings" on public.listings for all using (owner_id::text = auth.uid()::text) with check (owner_id::text = auth.uid()::text);
create policy "listing images are public" on public.listing_images for select using (true);
create policy "owners manage listing images" on public.listing_images for all using (exists (select 1 from public.listings l where l.id = listing_id and l.owner_id::text = auth.uid()::text)) with check (exists (select 1 from public.listings l where l.id = listing_id and l.owner_id::text = auth.uid()::text));
create policy "users manage their profile" on public.profiles for all using (id::text = auth.uid()::text) with check (id::text = auth.uid()::text);
create policy "categories are public" on public.categories for select using (is_active = true);
create policy "participants read messages" on public.messages for select using (sender_id::text = auth.uid()::text or receiver_id::text = auth.uid()::text);
create policy "users send messages" on public.messages for insert with check (sender_id::text = auth.uid()::text);
create policy "users read notifications" on public.notifications for select using (user_id::text = auth.uid()::text);
create policy "users mark notifications read" on public.notifications for update using (user_id::text = auth.uid()::text) with check (user_id::text = auth.uid()::text);

insert into storage.buckets (id, name, public) values ('listing-photos', 'listing-photos', true) on conflict (id) do nothing;
drop policy if exists "listing photos are public" on storage.objects;
drop policy if exists "authenticated users upload listing photos" on storage.objects;
drop policy if exists "users delete their listing photos" on storage.objects;
create policy "listing photos are public" on storage.objects for select using (bucket_id = 'listing-photos');
create policy "authenticated users upload listing photos" on storage.objects for insert to authenticated with check (bucket_id = 'listing-photos');
create policy "users delete their listing photos" on storage.objects for delete to authenticated using (bucket_id = 'listing-photos' and owner_id::text = auth.uid()::text);
