-- ============================================================
-- GoRentHive — complete Supabase Postgres schema
-- Peer-to-peer rental marketplace: 34 tables + RLS + seeds.
-- Run this in Supabase > SQL Editor.
-- ============================================================

create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- Clean up old partial pilot tables (empty placeholders from the
-- earlier starter schema). Dropping is safe: these had no data and
-- the correct definitions are recreated below with the `users`
-- table. Remove this block if you have real data in them.
-- ------------------------------------------------------------
drop table if exists public.profiles cascade;
drop table if exists public.listing_images cascade;
drop table if exists public.listings cascade;
drop table if exists public.listings_old cascade;
drop table if exists public.messages cascade;
drop table if exists public.notifications cascade;
drop table if exists public.categories cascade;

-- ------------------------------------------------------------
-- USERS
-- Primary key is a UUID that matches auth.users.id so that a
-- profile row is created for every authenticated user.
-- ------------------------------------------------------------
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  phone text unique,
  password_hash text,
  full_name text not null default '',
  avatar text,
  role text not null default 'user' check (role in ('user','admin')),
  is_owner boolean not null default false,
  is_business boolean not null default false,
  mobile_verified boolean not null default false,
  email_verified boolean not null default false,
  identity_status text not null default 'none' check (identity_status in ('none','pending','verified','rejected')),
  identity_level integer not null default 1,
  id_type text,
  id_number text,
  id_selfie text,
  address text,
  barangay text,
  city text,
  province text,
  latitude double precision,
  longitude double precision,
  location_status text not null default 'none' check (location_status in ('none','pending','verified')),
  location_verified_by text default '',
  location_verified_at bigint,
  vessel_rating double precision not null default 0,
  review_count integer not null default 0,
  successful_rentals integer not null default 0,
  cancelled_rentals integer not null default 0,
  rating_sum integer not null default 0,
  referral_code text,
  referred_by_user_id uuid references public.users(id),
  referrer_credit integer not null default 0,
  wallet_balance integer not null default 0,
  suspended boolean not null default false,
  banned boolean not null default false,
  banned_reason text default '',
  last_terms_accepted text default '',
  premium_until bigint,
  payout_preference text default '',
  payout_account text default '',
  payout_account_name text default '',
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists users_city_idx on public.users(city);
create index if not exists users_role_idx on public.users(role);
create index if not exists users_premium_until_idx on public.users(premium_until);
create index if not exists users_referral_code_idx on public.users(referral_code);

-- ------------------------------------------------------------
-- CATEGORIES / SUBCATEGORIES
-- ------------------------------------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  icon text default '',
  description text default '',
  color text default '',
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null
);
create index if not exists subcategories_category_id_idx on public.subcategories(category_id);

-- ------------------------------------------------------------
-- LISTINGS
-- ------------------------------------------------------------
create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.users(id) on delete cascade,
  category_id bigint references public.categories(id),
  subcategory_id bigint references public.subcategories(id),
  title text not null,
  description text default '',
  price_per_day integer not null check (price_per_day > 0),
  security_deposit integer not null default 0,
  estimated_value integer not null default 0,
  deposit_tier text not null default 'low' check (deposit_tier in ('low','medium','high')),
  availability_start bigint,
  availability_end bigint,
  location_barangay text,
  location_city text not null,
  location_province text,
  latitude double precision,
  longitude double precision,
  delivery_available boolean not null default false,
  pickup_available boolean not null default false,
  delivery_fee integer not null default 0,
  min_verification_level integer not null default 2,
  rules text default '',
  cancellation_policy text not null default 'standard' check (cancellation_policy in ('standard','flexible','strict')),
  condition text default '',
  accessories text default '',
  serial_number text,
  featured boolean not null default false,
  featured_until bigint,
  status text not null default 'active' check (status in ('draft','active','paused','removed')),
  is_bundle boolean not null default false,
  bundle_items text default '',
  view_count integer not null default 0,
  favorite_count integer not null default 0,
  rental_count integer not null default 0,
  created_at bigint not null,
  updated_at bigint not null
);
create index if not exists listings_owner_id_idx on public.listings(owner_id);
create index if not exists listings_category_id_idx on public.listings(category_id);
create index if not exists listings_status_idx on public.listings(status);
create index if not exists listings_title_idx on public.listings using gin (to_tsvector('english', title || ' ' || coalesce(description,'')));

create table if not exists public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  url text not null,
  is_primary boolean not null default false,
  sort_order integer not null default 0
);
create index if not exists listing_images_listing_id_idx on public.listing_images(listing_id);

create table if not exists public.listing_reviews (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  author_id uuid not null references public.users(id),
  rating integer not null check (rating between 1 and 5),
  comment text default '',
  created_at bigint not null
);
create index if not exists listing_reviews_listing_id_idx on public.listing_reviews(listing_id);

-- ------------------------------------------------------------
-- BOOKINGS / RENTAL
-- ------------------------------------------------------------
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_ref text not null unique,
  renter_id uuid not null references public.users(id),
  owner_id uuid not null references public.users(id),
  listing_id bigint not null references public.listings(id),
  start_date bigint not null,
  end_date bigint not null,
  rental_days integer not null,
  rental_fee integer not null,
  security_deposit integer not null default 0,
  delivery_fee integer not null default 0,
  delivery_requested boolean not null default false,
  pickup_option text not null default 'pickup',
  delivery_method text not null default 'pickup' check (delivery_method in ('pickup','lalamove')),
  delivery_distance_km double precision not null default 0,
  delivery_vehicle_type text default '',
  dropoff_address text default '',
  lalamove_fee integer not null default 0,
  platform_fee integer not null default 0,
  total_charged integer not null default 0,
  amount_due_owner integer not null default 0,
  status text not null default 'pending' check (status in ('pending','approved','rejected','active','returned','completed','disputed','cancelled')),
  escrow_payment boolean not null default false,
  escrow_released boolean not null default false,
  return_proposed_deduction integer not null default -1,
  return_proposed_reason text default '',
  return_proposed_by uuid,
  return_completed_at bigint,
  agreement_signed_renter boolean not null default false,
  agreement_signed_owner boolean not null default false,
  checkin_confirmed boolean not null default false,
  checkout_confirmed boolean not null default false,
  late_fee integer not null default 0,
  cancellation_reason text default '',
  cancelled_by uuid,
  created_at bigint not null,
  updated_at bigint not null
);
create index if not exists bookings_renter_id_idx on public.bookings(renter_id);
create index if not exists bookings_owner_id_idx on public.bookings(owner_id);
create index if not exists bookings_listing_id_idx on public.bookings(listing_id);
create index if not exists bookings_status_idx on public.bookings(status);
create unique index if not exists bookings_booking_ref_idx on public.bookings(booking_ref);

create table if not exists public.booking_items (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  listing_id bigint not null,
  title text not null,
  price_per_day integer not null,
  days integer not null
);
create index if not exists booking_items_booking_id_idx on public.booking_items(booking_id);

create table if not exists public.booking_reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  reviewer_id uuid not null references public.users(id),
  target_user_id uuid not null references public.users(id),
  rating integer not null check (rating between 1 and 5),
  comment text default '',
  created_at bigint not null,
  unique (booking_id, reviewer_id)
);

create table if not exists public.rental_agreements (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  listing_id bigint not null,
  body text not null,
  renter_signed_at bigint,
  owner_signed_at bigint,
  created_at bigint not null
);
create index if not exists rental_agreements_booking_id_idx on public.rental_agreements(booking_id);

create table if not exists public.condition_records (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  phase text not null check (phase in ('checkin','checkout')),
  uploaded_by uuid not null references public.users(id),
  photos text default '',
  serial_number text,
  accessories text default '',
  damage_notes text default '',
  confirmed_by_other uuid,
  confirmed_at bigint,
  created_at bigint not null
);
create index if not exists condition_records_booking_id_idx on public.condition_records(booking_id);

-- ------------------------------------------------------------
-- DELIVERY
-- ------------------------------------------------------------
create table if not exists public.delivery_requests (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  phase text not null check (phase in ('dispatch','return')),
  provider text not null default 'sandbox',
  provider_order_id text default '',
  status text not null default 'requested',
  vehicle_type text default 'motorcycle',
  distance_km double precision not null default 0,
  fee integer not null default 0,
  origin_address text default '',
  dropoff_address text default '',
  dropoff_lat double precision,
  dropoff_lng double precision,
  tracking_url text default '',
  proof_photo text default '',
  proof_signature text default '',
  driver_name text default '',
  driver_phone text default '',
  created_at bigint not null,
  updated_at bigint not null
);
create index if not exists delivery_requests_booking_id_idx on public.delivery_requests(booking_id);

create table if not exists public.meeting_points (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  point_name text not null,
  point_address text default '',
  latitude double precision,
  longitude double precision,
  proposed_by uuid not null references public.users(id),
  renter_confirmed boolean not null default false,
  owner_confirmed boolean not null default false,
  handover_confirmed_at bigint,
  created_at bigint not null,
  updated_at bigint not null
);
create index if not exists meeting_points_booking_id_idx on public.meeting_points(booking_id);

-- ------------------------------------------------------------
-- FINANCE
-- ------------------------------------------------------------
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  payment_ref text not null unique,
  user_id uuid not null references public.users(id),
  booking_id bigint references public.bookings(id),
  type text not null check (type in ('rental','deposit','refund','payout','platform_fee','featured','referral','withdrawal','topup')),
  method text not null default 'sandbox',
  status text not null default 'pending' check (status in ('pending','succeeded','failed','refunded','held','released')),
  gross_amount integer not null,
  platform_fee integer not null default 0,
  net_amount integer not null default 0,
  meta text default '{}',
  created_at bigint not null,
  updated_at bigint not null
);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists payments_booking_id_idx on public.payments(booking_id);
create unique index if not exists payments_payment_ref_idx on public.payments(payment_ref);

create table if not exists public.security_deposits (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id),
  renter_id uuid not null references public.users(id),
  owner_id uuid not null references public.users(id),
  amount integer not null,
  status text not null default 'held' check (status in ('pending','held','released','partially_deducted','disputed','refunded')),
  deduction integer not null default 0,
  released_at bigint
);
create index if not exists security_deposits_booking_id_idx on public.security_deposits(booking_id);

create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments(id),
  user_id uuid not null references public.users(id),
  amount integer not null,
  status text not null default 'pending',
  method text default '',
  account text default '',
  account_name text default '',
  bank_name text default '',
  account_holder text default '',
  payout_note text default '',
  created_at bigint not null
);
create index if not exists payouts_user_id_idx on public.payouts(user_id);

create table if not exists public.refunds (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id),
  payment_id bigint references public.payments(id),
  renter_id uuid not null references public.users(id),
  amount integer not null,
  reason text not null,
  status text not null default 'pending',
  method text default '',
  account text default '',
  account_name text default '',
  created_at bigint not null
);

create table if not exists public.ledger_entries (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id),
  user_id uuid references public.users(id),
  type text not null,
  amount integer not null,
  balance_after integer not null,
  meta text default '{}',
  created_at bigint not null
);
create index if not exists ledger_entries_user_id_idx on public.ledger_entries(user_id);
create index if not exists ledger_entries_booking_id_idx on public.ledger_entries(booking_id);
create index if not exists ledger_entries_created_at_idx on public.ledger_entries(created_at);

-- ------------------------------------------------------------
-- DISPUTES / MESSAGES / FAVORITES
-- ------------------------------------------------------------
create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id),
  reporter_id uuid not null references public.users(id),
  category text not null,
  description text default '',
  status text not null default 'open' check (status in ('open','under_review','resolved','dismissed','closed')),
  resolution text default '',
  evidence text default '{}',
  resolved_by uuid,
  resolved_at bigint,
  created_at bigint not null
);
create index if not exists disputes_booking_id_idx on public.disputes(booking_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id),
  sender_id uuid not null references public.users(id),
  receiver_id uuid not null references public.users(id),
  body text not null,
  warning text default '',
  is_read boolean not null default false,
  created_at bigint not null
);
create index if not exists messages_sender_id_idx on public.messages(sender_id);
create index if not exists messages_receiver_id_idx on public.messages(receiver_id);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id),
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at bigint not null,
  unique (user_id, listing_id)
);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  plan text not null check (plan in ('basic','plus','premium')),
  fee integer not null,
  starts_at bigint not null,
  ends_at bigint not null,
  status text not null default 'active',
  created_at bigint not null
);
create index if not exists promotions_listing_id_idx on public.promotions(listing_id);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.users(id),
  referred_id uuid not null references public.users(id),
  code text not null,
  status text not null default 'pending' check (status in ('pending','rewarded')),
  reward_amount integer not null default 0,
  created_at bigint not null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  link text default '',
  is_read boolean not null default false,
  created_at bigint not null
);
create index if not exists notifications_user_id_idx on public.notifications(user_id);

create table if not exists public.rent_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.users(id),
  title text not null,
  description text default '',
  category text default '',
  city text,
  latitude double precision,
  longitude double precision,
  start_date bigint,
  end_date bigint,
  budget integer,
  status text not null default 'open' check (status in ('open','fulfilled','closed')),
  created_at bigint not null
);
create index if not exists rent_requests_requester_id_idx on public.rent_requests(requester_id);

-- ------------------------------------------------------------
-- OTP / EMAIL VERIFICATION (phone + manual email verification)
-- ------------------------------------------------------------
create table if not exists public.otps (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  channel text not null default 'mobile' check (channel in ('mobile','email')),
  code_hash text not null,
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  expires_at bigint not null,
  used boolean not null default false,
  meta text default '{}',
  created_at bigint not null
);
create index if not exists otps_user_id_idx on public.otps(user_id);

create table if not exists public.email_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  token text not null,
  expires_at bigint not null,
  used boolean not null default false,
  created_at bigint not null
);
create index if not exists email_verifications_user_id_idx on public.email_verifications(user_id);

create table if not exists public.identity_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  id_type text,
  id_number text,
  id_front text,
  id_back text,
  selfie text,
  status text not null default 'pending',
  admin_note text,
  reviewed_by uuid,
  reviewed_at bigint,
  created_at bigint not null
);
create index if not exists identity_verifications_user_id_idx on public.identity_verifications(user_id);

-- ------------------------------------------------------------
-- ADMIN SETTINGS / LEGAL / AUDIT
-- ------------------------------------------------------------
create table if not exists public.admin_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text not null,
  updated_at bigint not null
);

create table if not exists public.terms_versions (
  id bigint generated by default as identity primary key,
  type text not null,
  version integer not null,
  title text not null,
  content text not null,
  created_at bigint not null,
  unique (type, version)
);

create table if not exists public.user_terms_acceptance (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  terms_type text not null,
  version integer not null,
  accepted_at bigint not null,
  unique (user_id, terms_type)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.users(id),
  action text not null,
  detail text default '',
  ip text default '',
  created_at bigint not null
);

create table if not exists public.featured_payments (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  user_id uuid not null references public.users(id),
  plan text not null,
  amount integer not null,
  status text not null default 'succeeded',
  created_at bigint not null
);

-- ------------------------------------------------------------
-- Trigger: create a profile row for a new auth user
-- ------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, full_name, role, is_owner, created_at, updated_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'user',
    coalesce((new.raw_user_meta_data ->> 'is_owner')::boolean, false),
    extract(epoch from now()) * 1000,
    extract(epoch from now()) * 1000
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================================
-- SEED DATA
-- ============================================================
insert into public.admin_settings (key, value, updated_at) values
('platform_percent','8',0),
('platform_min_fee','20',0),
('platform_max_fee','',0),
('premium_fee','1499',0),
('free_listing_limit','15',0),
('extra_listing_fee','10',0),
('featured_fee','49',0),
('featured_days','30',0),
('referral_reward','50',0),
('referrer_reward','50',0),
('featured_fee_basic','49',0),
('featured_fee_plus','99',0),
('featured_fee_premium','199',0),
('free_cancellation_hours','48',0),
('partial_cancellation_hours','24',0),
('platform_name','GoRentHive',0),
('platform_tagline','Need it? Rent it. Own it? Earn from it.',0),
('terms_version','1',0),
('max_verification_level','4',0),
('deposit_tier_low','300',0),
('deposit_tier_medium','1000',0),
('deposit_tier_high','3500',0),
('deposit_tier_low_max_value','3000',0),
('deposit_tier_medium_max_value','15000',0),
('lalamove_enabled','1',0),
('lalamove_base_fee','70',0),
('lalamove_per_km','20',0),
('lalamove_vehicle_motorcycle','0',0),
('lalamove_vehicle_car','120',0),
('lalamove_vehicle_truck','300',0),
('location_radius_options','5,10,25',0),
('require_location','1',0),
('trust_deposit_discount_enabled','1',0),
('trust_deposit_min_score','80',0),
('trust_deposit_discount_pct','50',0),
('review_dedup_enabled','1',0)
on conflict (key) do nothing;

insert into public.categories (name, slug, icon, description, color, sort_order) values
('Photography & Videography','photography','📷','Cameras, lenses, lighting','#2F6FED',1),
('Camping & Outdoor','camping','⛺','Tents, gear, recreation','#22A06B',2),
('Events & Party','events','🎉','Tables, chairs, sound, decor','#E5484D',3),
('Fashion & Formal Wear','fashion','👗','Gowns, suits, accessories','#9B59B6',4),
('Cars & Vehicles','cars','🚗','Cars, motorcycles, vehicles','#1B2430',5),
('Sports & Fitness','sports','⚽','Sports gear and equipment','#F5A623',6),
('Tools & Equipment','tools','🔧','Power tools and hardware','#7A8B99',7),
('Power & Emergency','power','🔋','Generators and emergency kit','#E8920C',8),
('Home','home','🏠','Home appliances and furniture','#C97A06',9),
('Baby & Family','baby','🍼','Baby and family items','#F97FB5',10),
('Technology','tech','💻','Laptops, gadgets, electronics','#2F6FED',11),
('Gaming','gaming','🎮','Consoles and games','#5B46D4',12),
('Construction','construction','🏗️','Construction equipment','#6B7280',13),
('Production','production','🎬','AV and production gear','#111827',14),
('Travel','travel','✈️','Luggage and travel gear','#0EA5E9',15),
('Special Occasions','special','🎁','Occasion-specific items','#F43F5E',16),
('Other','other','📦','Anything legal','#6B7280',17)
on conflict (slug) do nothing;

insert into public.subcategories (category_id, name)
select id, s.name from public.categories c
cross join (select unnest(array['Cameras','Lenses','Lighting','Audio','Drone']) as name) s
where c.slug='photography'
on conflict do nothing;

-- ============================================================
-- ROW LEVEL SECURITY
-- Only the anon (browser) key hits these. Financial tables
-- (bookings write, ledger, payments, payouts, refunds, deposits,
-- wallets, admin) are NOT insert/update-able by the browser.
-- The financial Express server uses the service_role key which
-- bypasses RLS entirely, so no server policies are needed here.
-- ============================================================
alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.listing_reviews enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_items enable row level security;
alter table public.booking_reviews enable row level security;
alter table public.rental_agreements enable row level security;
alter table public.condition_records enable row level security;
alter table public.delivery_requests enable row level security;
alter table public.meeting_points enable row level security;
alter table public.payments enable row level security;
alter table public.security_deposits enable row level security;
alter table public.payouts enable row level security;
alter table public.refunds enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.disputes enable row level security;
alter table public.messages enable row level security;
alter table public.favorites enable row level security;
alter table public.promotions enable row level security;
alter table public.referrals enable row level security;
alter table public.notifications enable row level security;
alter table public.rent_requests enable row level security;
alter table public.admin_settings enable row level security;
alter table public.terms_versions enable row level security;
alter table public.user_terms_acceptance enable row level security;
alter table public.audit_logs enable row level security;
alter table public.featured_payments enable row level security;
alter table public.otps enable row level security;
alter table public.email_verifications enable row level security;
alter table public.identity_verifications enable row level security;

-- ---- public read policies ----
-- SECURITY: `users` holds password_hash, email, phone, wallet_balance,
-- id_number and id_selfie. We only expose the SAFE public profile columns to
-- anon/authenticated read. The own user's private fields (email, phone,
-- wallet_balance) are served by the server /auth/me + /wallet endpoints using
-- the service_role key. Column-level privileges are enforced here.
drop policy if exists "users read public users" on public.users;
create policy "users read public users" on public.users for select using (true);
revoke select on public.users from anon, authenticated;
grant select (
  id, full_name, avatar, role, is_owner, is_business,
  mobile_verified, email_verified, identity_status, identity_level,
  address, barangay, city, province, latitude, longitude,
  location_status, location_verified_by, location_verified_at,
  vessel_rating, review_count, successful_rentals, cancelled_rentals,
  referral_code
) on public.users to anon, authenticated;

-- own-user private reads (email, phone, wallet_balance) allowed only for the
-- row matching the authenticated user; the value-level policy cannot inspect
-- columns, so we rely on these columns being non-selectable via the column
-- grants above and served through the server instead. Profile rows are created
-- by the SECURITY DEFINER handle_new_user trigger on auth signup.
revoke insert on public.users from anon, authenticated;

drop policy if exists "categories are public" on public.categories;
create policy "categories are public" on public.categories for select using (true);

drop policy if exists "subcategories are public" on public.subcategories;
create policy "subcategories are public" on public.subcategories for select using (true);

drop policy if exists "published listings are public" on public.listings;
create policy "published listings are public" on public.listings for select using (status = 'active' or owner_id = auth.uid());

drop policy if exists "listing images are public" on public.listing_images;
create policy "listing images are public" on public.listing_images for select using (true);

drop policy if exists "listing reviews are public" on public.listing_reviews;
create policy "listing reviews are public" on public.listing_reviews for select using (true);

drop policy if exists "rent requests are public" on public.rent_requests;
create policy "rent requests are public" on public.rent_requests for select using (status = 'open' or requester_id = auth.uid());

drop policy if exists "terms are public" on public.terms_versions;
create policy "terms are public" on public.terms_versions for select using (true);

drop policy if exists "admin settings are public" on public.admin_settings;
create policy "admin settings are public" on public.admin_settings for select using (true);

-- ---- authenticated write policies (non-financial) ----
drop policy if exists "users update their own profile" on public.users;
create policy "users update their own profile" on public.users for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "owners manage their listings" on public.listings;
create policy "owners manage their listings" on public.listings for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "owners manage listing images" on public.listing_images;
create policy "owners manage listing images" on public.listing_images for all using (exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid()));

drop policy if exists "users insert reviews" on public.listing_reviews;
create policy "users insert reviews" on public.listing_reviews for insert with check (author_id = auth.uid());

drop policy if exists "users post rent requests" on public.rent_requests;
create policy "users post rent requests" on public.rent_requests for insert with check (requester_id = auth.uid());

drop policy if exists "users close their rent requests" on public.rent_requests;
create policy "users close their rent requests" on public.rent_requests for update using (requester_id = auth.uid());

drop policy if exists "users send messages" on public.messages;
create policy "users send messages" on public.messages for insert with check (sender_id = auth.uid());

drop policy if exists "participants read messages" on public.messages;
create policy "participants read messages" on public.messages for select using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists "users read notifications" on public.notifications;
create policy "users read notifications" on public.notifications for select using (user_id = auth.uid());

drop policy if exists "users toggle favorites" on public.favorites;
create policy "users toggle favorites" on public.favorites for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---- booking table: browser may READ bookings they are party to ----
drop policy if exists "parties read bookings" on public.bookings;
create policy "parties read bookings" on public.bookings for select using (renter_id = auth.uid() or owner_id = auth.uid());

drop policy if exists "parties read booking items" on public.booking_items;
create policy "parties read booking items" on public.booking_items for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "parties read agreements" on public.rental_agreements;
create policy "parties read agreements" on public.rental_agreements for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "parties read condition records" on public.condition_records;
create policy "parties read condition records" on public.condition_records for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "parties read deliveries" on public.delivery_requests;
create policy "parties read deliveries" on public.delivery_requests for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "parties read meeting points" on public.meeting_points;
create policy "parties read meeting points" on public.meeting_points for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "parties read reviews" on public.booking_reviews;
create policy "parties read reviews" on public.booking_reviews for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "party reads financial rows" on public.payments;
create policy "party reads financial rows" on public.payments for select using (user_id = auth.uid());

drop policy if exists "party reads ledger" on public.ledger_entries;
create policy "party reads ledger" on public.ledger_entries for select using (user_id = auth.uid());

drop policy if exists "party reads disputes" on public.disputes;
create policy "party reads disputes" on public.disputes for select using (exists (select 1 from public.bookings b where b.id = booking_id and (b.renter_id = auth.uid() or b.owner_id = auth.uid())));

drop policy if exists "user reads own otps" on public.otps;
create policy "user reads own otps" on public.otps for select using (user_id = auth.uid());

drop policy if exists "user reads own email verifications" on public.email_verifications;
create policy "user reads own email verifications" on public.email_verifications for select using (user_id = auth.uid());

drop policy if exists "user reads own identity verifications" on public.identity_verifications;
create policy "user reads own identity verifications" on public.identity_verifications for select using (user_id = auth.uid());

-- admins: full read is done by the server via service_role (bypasses RLS),
-- which is why no admin row-police policy on users is needed here. A
-- `FOR SELECT` policy with a `from public.users` subquery would recurse.
drop policy if exists "admins read all" on public.users;

-- ============================================================
-- STORAGE: listing photos bucket
-- ============================================================
insert into storage.buckets (id, name, public) values ('listing-photos', 'listing-photos', true)
on conflict (id) do nothing;

drop policy if exists "listing photos are public" on storage.objects;
drop policy if exists "authenticated users upload listing photos" on storage.objects;
drop policy if exists "users delete their listing photos" on storage.objects;
create policy "listing photos are public" on storage.objects for select using (bucket_id = 'listing-photos');
create policy "authenticated users upload listing photos" on storage.objects for insert to authenticated with check (bucket_id = 'listing-photos');
create policy "users delete their listing photos" on storage.objects for delete to authenticated using (bucket_id = 'listing-photos' and owner_id = auth.uid()::text);

-- ============================================================
-- FINANCIAL RPC FUNCTIONS (SECURITY DEFINER)
-- Called via supabase.rpc() by the financial server.
-- `security definer` lets a limited-role caller perform these
-- privileged money movements without full table access.
-- ============================================================
create or replace function public.ledger_entry(
  p_booking_id bigint,
  p_user_id uuid,
  p_type text,
  p_amount integer,
  p_meta text default '{}'
)
returns table (entry_id bigint, new_balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  before_balance integer;
begin
  if p_user_id is not null then
    select coalesce(wallet_balance,0) into before_balance from public.users where id = p_user_id;
  else
    before_balance := 0;
  end if;

  insert into public.ledger_entries (booking_id, user_id, type, amount, balance_after, meta, created_at)
  values (p_booking_id, p_user_id, p_type, p_amount, before_balance + p_amount, p_meta,
          (extract(epoch from now())*1000)::bigint)
  returning id into entry_id;

  if p_user_id is not null then
    update public.users set wallet_balance = wallet_balance + p_amount, updated_at = (extract(epoch from now())*1000)::bigint
    where id = p_user_id;
  end if;

  new_balance := before_balance + p_amount;
  return query select entry_id, new_balance;
end;
$$;

-- SECURITY: these are SECURITY DEFINER (bypass RLS) and MUST only be callable
-- by the financial server's service_role connection. Granting them to
-- anon/authenticated would let any browser user mint/deduct wallet money.
revoke all on function public.ledger_entry(bigint, uuid, text, integer, text) from public;
revoke all on function public.ledger_entry(bigint, uuid, text, integer, text) from anon, authenticated;
grant execute on function public.ledger_entry(bigint, uuid, text, integer, text) to service_role;

create or replace function public.get_user_balance(p_user_id uuid)
returns integer
language sql
security definer
set search_path = public
as $$
  select coalesce(wallet_balance,0) from public.users where id = p_user_id;
$$;

revoke all on function public.get_user_balance(uuid) from public;
revoke all on function public.get_user_balance(uuid) from anon, authenticated;
grant execute on function public.get_user_balance(uuid) to service_role;
