-- GoRentHive marketplace pro experience
-- Flexible pricing, owner availability blocks, saved searches, notifications,
-- business verification, richer agreements/condition evidence and two-phase QR handover.

create table if not exists public.listing_pricing (
  listing_id bigint primary key references public.listings(id) on delete cascade,
  hourly_rate integer check (hourly_rate is null or hourly_rate > 0),
  daily_rate integer check (daily_rate is null or daily_rate > 0),
  weekly_rate integer check (weekly_rate is null or weekly_rate > 0),
  monthly_rate integer check (monthly_rate is null or monthly_rate > 0),
  hourly_enabled boolean not null default false,
  daily_enabled boolean not null default true,
  weekly_enabled boolean not null default false,
  monthly_enabled boolean not null default false,
  minimum_hours integer not null default 1 check (minimum_hours between 1 and 168),
  minimum_days integer not null default 1 check (minimum_days between 1 and 365),
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create table if not exists public.listing_availability_blocks (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  owner_id uuid not null references public.users(id) on delete cascade,
  start_at bigint not null,
  end_at bigint not null,
  note text not null default '',
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  check (end_at >= start_at)
);
create index if not exists listing_availability_blocks_listing_idx on public.listing_availability_blocks(listing_id,start_at,end_at);

create table if not exists public.saved_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null default 'Saved search',
  query_text text not null default '',
  category_id bigint references public.categories(id) on delete set null,
  city text not null default '',
  radius_km integer check (radius_km is null or radius_km between 1 and 100),
  max_price integer check (max_price is null or max_price >= 0),
  alerts_enabled boolean not null default true,
  last_checked_at bigint not null default 0,
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);
create index if not exists saved_searches_user_idx on public.saved_searches(user_id);

create table if not exists public.notification_preferences (
  user_id uuid primary key references public.users(id) on delete cascade,
  booking_updates boolean not null default true,
  messages boolean not null default true,
  saved_search_alerts boolean not null default true,
  reminders boolean not null default true,
  owner_opportunities boolean not null default true,
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create table if not exists public.business_verifications (
  user_id uuid primary key references public.users(id) on delete cascade,
  legal_name text not null default '',
  registration_type text not null default '' check (registration_type in ('','DTI','SEC','CDA','OTHER')),
  registration_reference text not null default '',
  tin_last4 text not null default '',
  business_address text not null default '',
  business_city text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  reviewer_id uuid references public.users(id) on delete set null,
  review_notes text not null default '',
  reviewed_at bigint,
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create table if not exists public.vehicle_rental_terms (
  listing_id bigint primary key references public.listings(id) on delete cascade,
  mileage_allowance_km integer not null default 0 check (mileage_allowance_km >= 0),
  excess_mileage_fee integer not null default 0 check (excess_mileage_fee >= 0),
  fuel_policy text not null default 'same_level',
  geographic_restrictions text not null default '',
  accident_procedure text not null default 'Stop safely, contact emergency services when needed, document the scene, and notify the owner and GoRentHive promptly.',
  damage_procedure text not null default 'Document damage in-app and preserve all evidence for owner and platform review.',
  traffic_ticket_liability text not null default 'The authorized driver is responsible for traffic violations incurred during the rental period, subject to applicable law.',
  toll_liability text not null default 'The renter is responsible for tolls incurred during the rental period.',
  impoundment_liability text not null default 'Costs caused by renter misuse or violations may be charged subject to evidence, agreement terms and applicable law.',
  prohibited_tnvs boolean not null default true,
  prohibited_courier boolean not null default true,
  prohibited_racing boolean not null default true,
  prohibited_sublease boolean not null default true,
  prohibited_unauthorized_driver boolean not null default true,
  prohibited_outside_zone boolean not null default true,
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create table if not exists public.vehicle_incidents (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  reporter_id uuid not null references public.users(id),
  incident_type text not null,
  description text not null default '',
  location_city text not null default '',
  evidence text not null default '[]',
  police_report_reference text not null default '',
  insurance_reference text not null default '',
  status text not null default 'open' check (status in ('open','under_review','resolved','closed')),
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);
create index if not exists vehicle_incidents_booking_idx on public.vehicle_incidents(booking_id);

create table if not exists public.booking_handover_tokens (
  booking_id bigint not null references public.bookings(id) on delete cascade,
  phase text not null check (phase in ('pickup','return')),
  token_hash text not null,
  pin_hash text not null,
  generated_by uuid not null references public.users(id) on delete cascade,
  scanned_by uuid references public.users(id) on delete set null,
  scanned_at bigint,
  renter_confirmed_at bigint,
  owner_confirmed_at bigint,
  expires_at bigint not null,
  attempts integer not null default 0 check (attempts between 0 and 20),
  used_at bigint,
  created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  primary key (booking_id, phase)
);

alter table public.messages add column if not exists attachments text not null default '[]';
alter table public.messages add column if not exists read_at bigint;
alter table public.notifications add column if not exists dedupe_key text not null default '';
create unique index if not exists notifications_user_dedupe_idx on public.notifications(user_id,dedupe_key) where dedupe_key <> '';

alter table public.condition_records add column if not exists checklist text not null default '{}';
alter table public.condition_records add column if not exists odometer_km integer;
alter table public.condition_records add column if not exists fuel_percent integer check (fuel_percent is null or fuel_percent between 0 and 100);
alter table public.condition_records add column if not exists evidence_hash text not null default '';

alter table public.rental_agreements add column if not exists snapshot_hash text not null default '';
alter table public.rental_agreements add column if not exists renter_signature_hash text not null default '';
alter table public.rental_agreements add column if not exists owner_signature_hash text not null default '';
alter table public.rental_agreements add column if not exists renter_device_hash text not null default '';
alter table public.rental_agreements add column if not exists owner_device_hash text not null default '';
alter table public.rental_agreements add column if not exists vehicle_terms text not null default '{}';

alter table public.bookings add column if not exists pricing_unit text not null default 'daily' check (pricing_unit in ('hourly','daily','weekly','monthly'));
alter table public.bookings add column if not exists pricing_rate_at_booking integer not null default 0;
alter table public.bookings add column if not exists rental_hours integer not null default 0;
alter table public.bookings add column if not exists pickup_handover_confirmed_at bigint;
alter table public.bookings add column if not exists return_handover_confirmed_at bigint;

-- Operational/private tables are server-controlled. Public marketplace clients
-- receive intentionally minimized shapes from REST endpoints.
foreach_table_placeholder_do_not_use text;
